<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Priority</name>
   <tag></tag>
   <elementGuidId>7d291ce1-abf3-412b-a213-a34a93269b51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[text()='Priority'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mud-typography mud-typography-body1 mud-inherit-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Priority</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panelFollowUp&quot;)/div[@class=&quot;mud-collapse-container mud-collapse-entered&quot;]/div[@class=&quot;mud-collapse-wrapper&quot;]/div[@class=&quot;mud-collapse-wrapper-inner&quot;]/div[@class=&quot;mud-expand-panel-content&quot;]/div[@class=&quot;mud-container mud-container-maxwidth-xl pa-0&quot;]/div[@class=&quot;mud-paper mud-paper-outlined mud-card pa-0&quot;]/div[@class=&quot;mud-card-content&quot;]/div[@class=&quot;mud-grid mud-grid-spacing-xs-3 mud-grid-justify-xs-flex-start&quot;]/div[@class=&quot;mud-grid-item mud-grid-item-xs-5&quot;]/div[@class=&quot;mud-select&quot;]/div[@class=&quot;mud-popover mud-popover-open mud-popover-bottom mud-paper mud-elevation-8&quot;]/div[@class=&quot;mud-list mud-list-padding&quot;]/div[@class=&quot;mud-list-item mud-list-item-gutters mud-list-item-clickable mud-ripple&quot;]/div[@class=&quot;mud-list-item-text&quot;]/p[@class=&quot;mud-typography mud-typography-body1 mud-inherit-text&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panelFollowUp']/div[2]/div/div/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[5]/div/p</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority'])[1]/following::p[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Notice:'])[1]/following::p[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update W/S'])[1]/preceding::p[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Associated Letters or Forms'])[1]/preceding::p[12]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div[2]/div/div[2]/div/div[5]/div/p</value>
   </webElementXpaths>
</WebElementEntity>
