<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Legacy - Inquiry - Login Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f311506b-9f4e-45a1-84a1-20af73b78cf8</testSuiteGuid>
   <testCaseLink>
      <guid>03edf91d-fdc6-4980-8386-6cc9449d3d63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Failure</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d4242ad0-cc87-455c-8979-664fea4bf5ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b6a1acd-21c9-441d-8342-abe38c7cb187</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f845c3ff-1c2d-4256-aebc-b32dec638b43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38b33116-0df2-4f78-bbbe-1558557446be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e9f8363-2fa6-4043-a167-b1b049c4f79c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48ac1daa-ff1f-4fb6-806b-212624ba9355</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>412b71c1-795a-4a05-aae1-018dd7d9b829</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e6204c1-c70a-4551-9e9e-00d16d0a19ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Window</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
