<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lead APN_mud-input-slot mud-input-roo_ff250c</name>
   <tag></tag>
   <elementGuidId>0f0e77e6-fc6e-418a-beda-1ae9d40c3b39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mud-input-slot.mud-input-root.mud-input-root-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mud-input-slot mud-input-root mud-input-root-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_941040c370114b5dab00cf86aa03e3cb&quot;)/div[2]/div[@class=&quot;mud-dialog-content&quot;]/div[@class=&quot;mud-input-control mud-input-input-control&quot;]/div[@class=&quot;mud-input-control-input-container&quot;]/div[@class=&quot;mud-input mud-input-text mud-input-underline&quot;]/input[@class=&quot;mud-input-slot mud-input-root mud-input-root-text&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_941040c370114b5dab00cf86aa03e3cb']/div[2]/div[4]/div[3]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
